version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    open-pull-requests-limit: 5
    reviewers:
      - "azmolpro"
    assignees:
      - "azmolpro"
    commit-message:
      prefix: "Deps"
      prefix-development: "DevDeps"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"

  # Enable version updates for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
    commit-message:
      prefix: "CI"
      include: "scope"
    labels:
      - "github-actions"
      - "automated"
